name: Mise à jour des films

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  update-films:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Exécuter le script
        run: python update_films.py

      - name: Commit et push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add films.json
          git commit -m 'Mise à jour automatique des horaires'
          git push
