name: Générer films.json

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Installer les dépendances Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécuter import-api.py
        run: |
          python import-api.py 2025-09-01 2025-09-30

      - name: Vérifier la génération de films.json
        run: |
          ls -l films.json
          head -n 20 films.json
